# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: me
      POSTGRES_USER: me
      POSTGRES_DB: audyx
    ports:
     - 5433:5432
    volumes:
     - ./:/app
  tf:
    image: tensorflow/tensorflow:latest-py3
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/notebooks
      - ./python-scripts:/python-scripts
  